DELETE http://localhost:3003/api/blogs/62d64e24724e1ae422405e9a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3R0aSIsImlkIjoiNjJkNjU5MTNhNTNjNzk3NmRjN2UyZjRjIiwiaWF0IjoxNjU4MjIzMTM2LCJleHAiOjE2NTgyMjY3MzZ9.qF5maRe8XY3tH6Hbs1_rSD8WZovehbDzedIvcaSta_E
