PUT http://localhost:3003/api/blogs/62d662f9a15bfaba4db66d4a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3R0aSIsImlkIjoiNjJkNjU5MTNhNTNjNzk3NmRjN2UyZjRjIiwiaWF0IjoxNjU4MjE3MTMxfQ.BFy9S8fbxB2gsIFTRvo_67lXruGiYIZbqMyMrKkQ9Jk

{
    "title":"AuthorizedLollero",
    "author":"0505995008",
    "url":"www.example.com",
    "likes":20
}